### ISSUE TITLE
Compile Errors with current Arduino ESP8266 on PlatformIO

### ISSUE THREAD

**Issue by jclds139** [CreativeRobotics/Commander#10]
Apparently several of the internal functions have unused values and at least one doesn't guarantee a return value for a non-void function, which is now treated as an error in PlatformIO so the library won't compile.
If it helps, here's the relevant errors from `pio run`

```
Compiling .pio/build/nodemcu/lib8e8/Commander/Commander.cpp.o
Compiling .pio/build/nodemcu/lib8e8/Commander/utilities/CommandHelpTags.cpp.o
.pio/libdeps/nodemcu/Commander/src/utilities/CommandHelpTags.cpp: In function 'bool getCommandArgCode(char*, cmdArgs_t)':
.pio/libdeps/nodemcu/Commander/src/utilities/CommandHelpTags.cpp:11:25: warning: NULL used in arithmetic [-Wpointer-arith]
   11 |  while(helpText[idx] != NULL){
      |                         ^~~~
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In constructor 'Commander::Commander()':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:10:34: warning: list-initializer for non-class type must not be parenthesized
   10 |                         "errors"}){
      |                                  ^
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In constructor 'Commander::Commander(uint16_t)':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:24:46: warning: list-initializer for non-class type must not be parenthesized
   24 |                                     "errors"}){
      |                                              ^
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In member function 'uint8_t Commander::countItems()':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:527:7: warning: unused variable 'state' [-Wunused-variable]
  527 |  bool state = 0;
      |       ^~~~~
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In member function 'uint8_t Commander::getLength(uint8_t)':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:658:44: warning: NULL used in arithmetic [-Wpointer-arith]
  658 |   if(commandList[indx].commandString[n] != NULL) length++;
      |                                            ^~~~
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In member function 'bool Commander::checkCommand(uint16_t)':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:940:27: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  940 |  if(bufferString.length() < commandLengths[cmdIdx]+1) return false; //no match if the buffer is shorter than the command+1 (buffer will have the end of line char)
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In member function 'bool Commander::itemToNextDelim()':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:1243:7: warning: unused variable 'endOnQuote' [-Wunused-variable]
 1243 |  bool endOnQuote = false;
      |       ^~~~~~~~~~
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In member function 'bool Commander::isItem(char)':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:1282:11: warning: NULL used in arithmetic [-Wpointer-arith]
 1282 |  if(ch == NULL) return false;
      |           ^~~~
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In member function 'uint8_t Commander::getInternalCmdLength(const char*)':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:1461:19: warning: NULL used in arithmetic [-Wpointer-arith]
 1461 |   if(intCmd[n] == NULL) return n;
      |                   ^~~~
.pio/libdeps/nodemcu/Commander/src/Commander.cpp: In member function 'uint8_t Commander::getLength(uint8_t)':
.pio/libdeps/nodemcu/Commander/src/Commander.cpp:661:1: error: control reaches end of non-void function [-Werror=return-type]
```
So, can you make sure that non-void member functions always have a return value?

**Comment by embedded-creations** [comment]
I found the same thing when compiling for ESP32:

- `getLength()` needs a `	return length;`  for the last line of the method
- I had to wrap the new `availableForWrite()` method with `#if !defined(ESP8266) && !defined(ESP32)` as this isn't included as part of the ESP32's Stream class (and I'm guessing not ESP8266 either.  There's probably a better definition check as there are now more ESP devices out, but my lazy fix was good enough for me

**Comment by embedded-creations** [comment]
Improvement so that Commander's API is consistent:

```
	int availableForWrite() {
#if !defined(ESP8266) && !defined(ESP32)
		return ports.outPort ? ports.outPort->availableForWrite() : 0;
#else
		// availableForWrite() is not part of the Stream class on ESP32 (and probably ESP8266)
		return 0;
#endif
	}
```

**Comment by CreativeRobotics** [comment]
Thanks, I have updated the code for the latest release and all these issues should be fixed now.

**Comment by embedded-creations** [comment]
@CreativeRobotics don't forget to update the version number (for 4.2.1) in library.properties and commit.  https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

**Comment by CreativeRobotics** [comment]
Oops, yes, not the first time I forgot to do that either. I decided to delete the two releases and re-release the 4.2.0 one with everything in it. Thanks for pointing out the error!

**Comment by embedded-creations** [comment]
Not sure if that will work, but it would be the cleanest solution: " The version property in library.properties must not be the same as it was in a tag previously added to the Library Manager index."

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

Worth a shot!

I have an (out of date and messy, otherwise I'd share it with you) checklist for Arduino Library Manager releases, as there's too many things to forget or do in the wrong order if I try to do it from memory

**Comment by CreativeRobotics** [comment]
Unfortunatly it didn't work. I'll bump it up a version ..

**Comment by CreativeRobotics** [comment]
Hopefully this will work - update to 4.2.2 - not having the best day, too much heat, and both kids at home feeling bored.

**Comment by embedded-creations** [comment]
I hear you, I'm sitting in front of a fan to cool off and haven't had much luck actually getting any work done
