### ISSUE TITLE
Unable to use library with Putty.

### ISSUE THREAD

**Issue by peddamat** [CreativeRobotics/Commander#13]
I flashed the 'BasicCommands' example to my ESP32 board.  From the Arduino Serial Monitor, I'm able to use the library wonderfully.  However, if I try to connect to the serial port using Putty, or the Visual Studio Code "Serial Monitor", entered commands aren't registered.

**Comment by CreativeRobotics** [comment]
Check that the terminal is sending a line feed character (0x0a) at the end of the command.

**Comment by peddamat** [comment]
That did solve the issue, thank you!

**Comment by CreativeRobotics** [comment]
Incidentally, the line feed character is not hard coded into Commander, so you can change it to something else if you want to ... not that there is much reason to.
