### ISSUE TITLE
typo in Commander/src/Commander.h  => not compiling

### ISSUE THREAD

**Issue by barzilouik** [CreativeRobotics/Commander#2]
`#include "utilities\CommandHelpTags.h"`

is containing a \  thus not compiling on my linux box for version 3.1.0 of Commander

**Comment by CreativeRobotics** [comment]
Thanks - fixed this, will check for other instances of this issue (I develop on Windows which is agnostic about slash directions.)

**Comment by CreativeRobotics** [comment]
It may take 24 hours before the new release appears in the Arduino library manager.
