### ISSUE TITLE
Arduino Library Manager latest release doesn't compile

### ISSUE THREAD

**Issue by embedded-creations** [CreativeRobotics/Commander#6]
Hi, I just found your very impressive library by searching "CLI" in Arduino Library Manager, but when I tried to compile an example it failed because `setUserString()` was missing.  I see from the commit history that the 4.1.0 tag was made for the the commit before `setUserString()` was added.  I believe you need to update library.properties with a new number, commit, and tag that commit to get a working copy of the latest code into Arduino Library Manager.

I was able to checkout the latest from GitHub and compile so I'm not stuck.

**Comment by embedded-creations** [comment]
Also I noticed the README has some problems, it looks like there's two versions of the README mixed in with each other.  Sections are repeated with slightly different content

**Comment by CreativeRobotics** [comment]
Thanks for the feedback, the last release got a bit mangled!
Hopefully this is now fixed and relseas 4.1.1 should compile. The README is also fixed.
